---

- type: replace
  path: /instance_groups/name=mosquitto/jobs/name=mosquitto/properties?/ssl/enabled
  value: true

- type: replace
  path: /instance_groups/name=mosquitto/jobs/name=mosquitto/properties?/ssl/port
  value: 8883

- type: replace
  path: /instance_groups/name=mosquitto/jobs/name=mosquitto/properties?/ssl/ca_certificate
  value: ((mosquitto-ca.certificate))

- type: replace
  path: /instance_groups/name=mosquitto/jobs/name=mosquitto/properties?/ssl/private_key
  value: ((mosquitto-tls.private_key))

- type: replace
  path: /instance_groups/name=mosquitto/jobs/name=mosquitto/properties?/ssl/certificate
  value: ((mosquitto-tls.certificate))

- type: replace
  path: /variables?/-
  value:
    name: mosquitto-ca
    type: certificate
    options:
      is_ca: true
      common_name: mosquittoCA

- type: replace
  path: /variables?/-
  value:
    name: mosquitto-tls
    type: certificate
    options:
      ca: mosquitto-ca
      common_name: mosquitto
      alternative_names:
      - 127.0.0.1
      - "*.mosquitto.default.mosquitto.bosh"
